/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author sissysebas
 */
public class FrmEjemplo extends javax.swing.JDialog {

    /**
     * Creates new form FrmEjemplo
     */
    public FrmEjemplo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_b = new javax.swing.JTextField();
        txt_resp = new javax.swing.JTextField();
        btn_sumar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("TeX Gyre Termes Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 237, 25));
        jLabel1.setText("Numero A:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 50, 90, 18);

        txt_a.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_a.setText("0");
        jPanel1.add(txt_a);
        txt_a.setBounds(130, 40, 230, 28);

        jLabel2.setFont(new java.awt.Font("TeX Gyre Termes Math", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 237, 25));
        jLabel2.setText("Numero B:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 110, 90, 18);

        txt_b.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_b.setText("0");
        jPanel1.add(txt_b);
        txt_b.setBounds(130, 100, 230, 28);

        txt_resp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_resp.setText("0");
        txt_resp.setEnabled(false);
        jPanel1.add(txt_resp);
        txt_resp.setBounds(224, 160, 120, 28);

        btn_sumar.setText("SUMAR");
        btn_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sumar);
        btn_sumar.setBounds(102, 170, 100, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 380, 220);

        setSize(new java.awt.Dimension(410, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumarActionPerformed
        // TODO add your handling code here:
        try {
            Double a = new Double(txt_a.getText());
            Double b = new Double(txt_b.getText());
            BigDecimal suma = new BigDecimal(a);
            suma = suma.add(new BigDecimal(b));
            txt_resp.setText(suma.toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error de entrada de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_sumarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEjemplo dialog = new FrmEjemplo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_resp;
    // End of variables declaration//GEN-END:variables
}
